version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      discovery.type: single-node
      ELASTIC_PASSWORD: "Letmein123!"
    ports:
      - "9200:9200"
      - "9300:9300"
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.11.2
  #   command: filebeat -e -strict.perms=false
  #   volumes:
  #     - type: bind
  #       source: ./beats/filebeat.yml
  #       target: /usr/share/filebeat/filebeat.yml
  #       read_only: true
  #     - type: bind
  #       source: ./beats/netflow.yml
  #       target: /usr/share/filebeat/netflow.yml
  #       read_only: true
  #   ports:
  #     - "2055:2055"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch
  
  # flow-collector:
  #   image: elastiflow/flow-collector:5.0.0
  #   container_name: flow-collector
  #   #restart: 'unless-stopped'
  #   network_mode: 'host'
  #   volumes:
  #     - /etc/elastiflow:/etc/elastiflow
  #   environment:
  #     EF_FLOW_OUTPUT_ELASTICSEARCH_ENABLE: 'true'
  #     EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_OVERWRITE: 'true'
  #     EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_SHARDS: 1
  #     EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_REPLICAS: 0
  #     EF_FLOW_OUTPUT_ELASTICSEARCH_ADDRESSES: 'elasticsearch:9200'
  #     EF_FLOW_OUTPUT_ELASTICSEARCH_USERNAME: 'elastic'
  #     EF_FLOW_OUTPUT_ELASTICSEARCH_PASSWORD: 'Letmein123!'

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch: