version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
      - certs: $CERTS_DIR
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      discovery.type: single-node
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      xpack.license.self_generated.type=trial 
      xpack.security.enabled=true
      xpack.security.http.ssl.enabled=true
      xpack.security.http.ssl.key: $CERTS_DIR/es01/es01.key
      xpack.security.http.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.http.ssl.certificate: $CERTS_DIR/es01/es01.crt
      xpack.security.transport.ssl.verification_mode: certificate 
      xpack.security.transport.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.transport.ssl.certificate: $CERTS_DIR/es01/es01.crt
      xpack.security.transport.ssl.key: $CERTS_DIR/es01/es01.key
    ports:
      - "9200:9200"
      - "9300:9300"
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:${VERSION}
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:${VERSION}
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch: