# config/pipelines.yml
- pipeline.id: beats-server
  config.string: |
    input { beats { port => "5044" } }
    output {
        if "checkpoint" in [tag] {
          pipeline { send_to => "checkpoint" }
        } else if "fortinet" in [tag] {
          pipeline { send_to => "fortinet" }
        }
- pipeline.id: checkpoint-processing
  path.config: "/etc/logstash/conf.d/checkpointpipe.conf"
- pipeline.id: fortinet-processing
  path.config: "/etc/logstash/conf.d/fortinetpipe.conf"
